<a href="https://colab.research.google.com/github/Aliweb789/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
print([pd.__version__])

['2.2.3']

In [4]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche"],
  'counts': [3, 7, 2, 4, 3, 5, 6]
}


df = pd.DataFrame(mydataset)

print(df)

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [33]:
df.head(7) # default 5 rows --> -1 bolsa ohirgisidan tashqari hammasini chiqaradi, 0- column name larni chiqaradi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [6]:
df.tail() # oxiridan boshlab 5 rows sanaydi

      cars  counts
2     Ford       2
3  Bugatti       4
4  Ferarri       3
5   Nissan       5
6  Porsche       6

In [7]:
df.shape

(7, 2)

In [8]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [9]:
df.dtypes

cars      object
counts     int64
dtype: object

In [10]:
df.describe() # numerical columns only (std --raqamlar bir biridan farqi)

         counts
count  7.000000
mean   4.285714
std    1.799471
min    2.000000
25%    3.000000
50%    4.000000
75%    5.500000
max    7.000000

In [11]:
df.describe(include="all")

       cars    counts
count     7  7.000000
unique    7       NaN
top     BMW       NaN
freq      1       NaN
mean    NaN  4.285714
std     NaN  1.799471
min     NaN  2.000000
25%     NaN  3.000000
50%     NaN  4.000000
75%     NaN  5.500000
max     NaN  7.000000

In [12]:
df.iloc[2:4] # 2 qatordan 4 qatorgacha bo'lgan indexlarni olib keladi. [3:] = 3-qatordan boshlab oxirigacha bo'lgan indexni oladi!

      cars  counts
2     Ford       2
3  Bugatti       4

In [13]:
df.loc[:, "cars"] #nechta qatorni kormoqchimiz, qaysi columndagi maumot

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
Name: cars, dtype: object

In [14]:
df['counts'] > 4

0    False
1     True
2    False
3    False
4    False
5     True
6     True
Name: counts, dtype: bool

In [15]:
df[df['counts'] > 4] # bu holatda boolean qaytarmasdan faqat 4 dan katta bo'lganlarni oladi!

      cars  counts
1    Volvo       7
5   Nissan       5
6  Porsche       6

In [16]:
df.mean(numeric_only=True)
# df['counts'].mean() # mana bu holatda ham ishlatish mumkin!

counts    4.285714
dtype: float64

In [17]:
df.sum() # yeg'indini chiqaradi!

cars      BMWVolvoFordBugattiFerarriNissanPorsche
counts                                         30
dtype: object

In [18]:
df.min()

cars      BMW
counts      2
dtype: object

In [19]:
df.max()

cars      Volvo
counts        7
dtype: object

In [20]:
df.median(numeric_only=True) #middle value ni olib beradi

counts    4.0
dtype: float64

In [21]:
df.count() #null data yoqligini chiqarib beradi

cars      7
counts    7
dtype: int64

In [22]:
df.std(numeric_only=True)

counts    1.799471
dtype: float64

In [23]:
data_with_missing ={
    "cars": ["BMW", "Volvo", None, "Bugatti", "Ferarri", None, "Porsche"],
    "counts": [None, 7, 5, 4, 3, None, 9]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5     None     NaN
6  Porsche     9.0

In [24]:
df_missing.isnull() #null valuelarni true qilib chiqaradi

    cars  counts
0  False    True
1  False   False
2   True   False
3  False   False
4  False   False
5   True    True
6  False   False

In [25]:
df_missing.isnull().sum() #datasi yoq column larni chiqarib beradi

cars      2
counts    2
dtype: int64

In [26]:
df_missing.dropna() #datasi yoqlarni ochirib beradi

      cars  counts
1    Volvo     7.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [27]:
df_missing.dropna(how="all") #rowda toliq data yoq bolsa ochiradi

      cars  counts
0      BMW     NaN
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [28]:
df_missing.dropna(axis=1) #column boyicha data yoq bolsa ochirib yuboradi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [29]:
df_missing.dropna(subset=["counts"]) # faqat counts columns ni tekshiradi!

      cars  counts
1    Volvo     7.0
2     None     5.0
3  Bugatti     4.0
4  Ferarri     3.0
6  Porsche     9.0

In [30]:
df_missing.fillna(0) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2        0     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5        0     0.0
6  Porsche     9.0

In [31]:
df_missing.fillna({"cars": "unknow", "counts": 0}) # None qatorlarga data joylaydi

      cars  counts
0      BMW     0.0
1    Volvo     7.0
2   unknow     5.0
3  Bugatti     4.0
4  Ferarri     3.0
5   unknow     0.0
6  Porsche     9.0

In [34]:
df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
df.to_excel("test.xlsx")

In [38]:
# df = pd.read_csv("Titanic-Dataset.csv")

df = pd.read_excel("test.xlsx")
df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [39]:
# Series => 1D
cars = pd.Series(["BMW", "Volvo", "Ford", "Bugatti", "Ferarri", "Nissan", "Porsche"])
print(cars)

0        BMW
1      Volvo
2       Ford
3    Bugatti
4    Ferarri
5     Nissan
6    Porsche
dtype: object

In [40]:
cars_serise = data_with_missing["cars"]
print(cars_serise)

['BMW', 'Volvo', None, 'Bugatti', 'Ferarri', None, 'Porsche']